### ISSUE TITLE
Molad Sensor not Updating

### ISSUE THREAD

**Issue by salonluden** [chaimchaikin/molad-hacs#1]
Hi,

HAOS, versions:
Core: 2024.2.5
Supervisor: 2024.02.1
Operating System: 12.0
Frontend: 20240207.1

Sensor hasnt updated since Tishrei

**Comment by chaimchaikin** [comment]
Its a bug with the Adar II in a leap year, I'll work on that. Thanks for finding!

**Comment by chaimchaikin** [comment]
@salonluden resolved in v0.3.3 https://github.com/chaimchaikin/molad-ha/releases/tag/v0.3.3

(If you don't see the update in Home Assistant Updates, go to the Repository View - the page with details about the element - click the "kebab" menu in the top-right corner and choose "Update information" from the dropdown.)

**Comment by salonluden** [comment]
Fantastic thanks for the quick fix.
