### ISSUE TITLE
[Feature Enhancement Request] Upcoming Shabbat is Mevorchim

### ISSUE THREAD

**Issue by salonluden** [chaimchaikin/molad-hacs#2]
Hi Chaim,

Simple feature enhancement that I think can make this sensor more useful. 
Currently, my (and I'm guessing others) usage requires looking ahead to see if the upcoming shabbat is a shabbat mevorchim, (which I do so using pyluach), and not just knowing if _now_ is shabbat mevorchim. If there could be an attribute similar to Iis_upcoming_shabbos_mevorchim that would be amazing.

Thanks!

**Comment by chaimchaikin** [comment]
Added in the latest release https://github.com/chaimchaikin/molad-ha/releases/tag/v.0.3.4
Enjoy :)

**Comment by salonluden** [comment]
Looks great thanks for the fast response!
