### ISSUE TITLE
Not showing any entities 

### ISSUE THREAD

**Issue by powertbs** [chaimchaikin/molad-hacs#4]
When you install the integration it will not show any entries underneath even though it's in already 

![Screenshot 2024-06-07 164539](https://github.com/chaimchaikin/molad-ha/assets/54761289/578e8108-d1d0-4386-8c10-bf17f0ba3ae2)

In the meantime I would like to see if you can add a Rosh Chidis sensor if it is Rosh Chodish and what day of Rosh Chodish it is 

Thank you

**Comment by chaimchaikin** [comment]
@powertbs can you share what version of Home Assistant you are running? Also are there any relevant logs?

I'll look into adding a Rosh Chodesh sensor when I have time to work on this, have you tried other jewish calendar components such as https://github.com/rt400/Jewish-Sabbaths-Holidays - do they have rosh chodesh info?

**Comment by salonluden** [comment]
Version 0.3.4 of Molad Sensor, Home assistant version 2024.06.04 not showing any sensors either...

**Comment by teadragon7** [comment]
same issue

**Comment by teadragon7** [comment]
not sure what changed but it works now

**Comment by salonluden** [comment]
Mines still failing:
```
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 366, in _async_setup_platform
    await asyncio.shield(awaitable)
  File "/config/custom_components/molad/sensor.py", line 18, in async_setup_entry
    MoladSensor(hass),
    ^^^^^^^^^^^^^^^^^
  File "/config/custom_components/molad/sensor.py", line 67, in __init__
    BaseSensor.__init__(self, "molad", hass)
  File "/config/custom_components/molad/sensor.py", line 44, in __init__
    self.update_sensor()
  File "/config/custom_components/molad/sensor.py", line 71, in update_sensor
    m = self.molad.get_molad(d)
        ^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/molad/helper.py", line 336, in get_molad
    is_upcoming_shabbos_mevorchim = self.is_upcoming_shabbos_mevorchim(date)
                                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/molad/helper.py", line 310, in is_upcoming_shabbos_mevorchim
    return self.is_shabbos_mevorchim(upcoming_saturday_at_midnight)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/molad/helper.py", line 302, in is_shabbos_mevorchim
    and h.month != hdate.htables.Months.Elul
                   ^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: type object 'Months' has no attribute 'Elul'. Did you mean: 'ELUL'?

```

**Comment by teadragon7** [comment]
this issue came back when i updated my system currently running 
Core
2024.7.3
Supervisor
2024.06.2
Operating System
12.4

**Comment by salonluden** [comment]
Still have the issue on 2024.11.2

**Comment by powertbs** [comment]
I had the sensors more than ones and couldn't delete them because it
doesn't have a unique ID so I deleted the integration and installed it
again only 3 sensors are coming in

**Comment by chaimchaikin** [comment]
@powertbs @salonluden @teadragon7 this should now be fixed in latest version (0.3.5) was due to an breaking change on a dependency

**Comment by chaimchaikin** [comment]
> I had the sensors more than ones and couldn't delete them because it doesn't have a unique ID so I deleted the integration and installed it again but only 3 sensors are coming in

your attached picture did not come through, if you're still having this issue after latest update can you try share again?

**Comment by salonluden** [comment]
> @powertbs @salonluden @teadragon7 this should now be fixed in latest version (0.3.5) was due to an breaking change on a dependency

Amazing I already see that it works. Thanks!!!

**Comment by powertbs** [comment]
![Screenshot 2024-12-01 123908](https://github.com/user-attachments/assets/5c7d5f13-6fa6-4f6a-a32b-0c82f7b05a42)

Here is the picture 

And as a BTW I updated to 0.3.5 and only those 3 sensors are showing

**Comment by chaimchaikin** [comment]
> ![Screenshot 2024-12-01 123908](https://private-user-images.githubusercontent.com/54761289/391357843-5c7d5f13-6fa6-4f6a-a32b-0c82f7b05a42.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzMwOTIyNDksIm5iZiI6MTczMzA5MTk0OSwicGF0aCI6Ii81NDc2MTI4OS8zOTEzNTc4NDMtNWM3ZDVmMTMtNmZhNi00ZjZhLWEzMmItMGM4MmY3YjA1YTQyLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEyMDElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMjAxVDIyMjU0OVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTI3N2RjZjU1ODg0MTFhNjQ5ZTcwMzZiMTJkMjYyODA4MmE1ZDllNzdlMGI1YTRkZWQ1ZDU3NDJkYzE3NjQ0ZTEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.uRDRXLlP11M-J9Cgcaq7zmwmAvNk4mjaynCUFSmoFVY)
> 
> Here is the picture
> 
> And as a BTW I updated to 0.3.5 and only those 3 sensors are showing

this looks correct (mine looks the same), there are 3 sensors, additional information is available in the Molad sensor (sensor.molad) as attributes.
Here's an example of a markdown card I have to show the info:

```
type: conditional
conditions:
  - entity: sensor.is_shabbos_mevorchim
    state: 'True'
card:
  type: markdown
  content: >
    ## Shabbos Mevorchim {{ state_attr('sensor.molad', 'month_name')
    }}

    The molad will be on **{{ state_attr('sensor.molad', 'friendly')
    }}**

    Rosh Chodesh is on **{{ state_attr('sensor.molad', 'rosh_chodesh')
    }}**
```

(this was setup before ha added conditions directly into cards, so you can probably set up the hide/show with a condition directly on the markdown card instead of using the conditional card)

**Comment by chaimchaikin** [comment]
You can also click on the Molad sensor entity and expand attributes to see all the attributes (the [usage section in the readme](https://github.com/chaimchaikin/molad-ha?tab=readme-ov-file#usage) has the full list):
![image](https://github.com/user-attachments/assets/b6379be6-af7d-4db8-bff5-cf268e2e227c)
