### ISSUE TITLE
Date on Rosh Jodesh

### ISSUE THREAD

**Issue by jbrandek** [chaimchaikin/molad-hacs#5]
Hi Chaim,

It would be possible to add the date also for Rosh Jodesh?
Like 
Tuesday 3 September 2024 and Wednesday, 4 September 2024 

instead of 
Rosh chodesh Tuesday & Wednesday
Rosh chodesh days Tuesday, Wednesday

**Comment by chaimchaikin** [comment]
Added in https://github.com/chaimchaikin/molad-ha/releases/tag/v0.4.0
